apiVersion: apps/v1
kind: Deployment
metadata:
  name: nsqadmin-deployment
  namespace: nsq
  labels:
    app: nsqadmin-lab
spec:
  selector:
    matchLabels:
      app: nsqadmin-lab
  replicas: 1
  template:
    metadata:
      labels:
        app: nsqadmin-lab
    spec:
      containers:
        - name: nsqadmin
          image: nsqio/nsq
          command:
            - /bin/sh
            - '-c'
            - >-
              /nsqadmin 
              --lookupd-http-address=nsqlookupd-statefulset-0.nsqlookupd-svc.nsq.svc.cluster.local:4161
              --lookupd-http-address=nsqlookupd-statefulset-1.nsqlookupd-svc.nsq.svc.cluster.local:4161
              --lookupd-http-address=nsqlookupd-statefulset-2.nsqlookupd-svc.nsq.svc.cluster.local:4161
          ports:
            - name: port-4171
              containerPort: 4171
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: nsqadmin-svc
  namespace: nsq
  labels:
    app: nsqadmin-lab-svc
spec:
  type: NodePort
  ports:
    - name: port-svc-4171
      port: 4171
      targetPort: 4171
      protocol: TCP
  selector:
    app: nsqadmin-lab
