apiVersion: v1
kind: Service
metadata:
  name: nsqlookupd-svc
  namespace: nsq
  labels:
    app: lookupd-lab-svc
spec:
  type: NodePort
  ports:
    - name: port-svc-4160
      port: 4160
      targetPort: 4160
      protocol: TCP
    - name: port-svc-4161
      port: 4161
      targetPort: 4161
      protocol: TCP
  selector:
    app: lookupd-lab
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nsqlookupd-statefulset
  namespace: nsq
  labels:
    app: lookupd-lab
spec:
  selector:
    matchLabels:
      app: lookupd-lab
  serviceName: nsqlookupd-svc
  replicas: 3
  template:
    metadata:
      labels:
        app: lookupd-lab
    spec:
      containers:
        - name: nsqlookupd
          image: nsqio/nsq
          command:
            - /bin/sh
            - '-c'
            - >-
              /nsqlookupd
          ports:
            - name: port-4160
              containerPort: 4160
              protocol: TCP
            - name: port-4161
              containerPort: 4161
              protocol: TCP
